language: node_js
node_js:
  - '10'

cache:
  directories:
    - 'node_modules'

script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  local-dir: build
  repo: danakt/minesweeper
  target-branch: gh-pages
  on:
    branch: master
